version: '3.8'

services:
  # Oracle Database service
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-books-db
    environment:
      - ORACLE_PWD=Maya
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./infrastructure/src/main/resources/db/scripts:/opt/oracle/scripts/setup
    ports:
      - "1521:1521"
      - "5500:5500"
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "Maya/Maya@//localhost:1521/XE", "AS", "SYSDBA", "<<< 'SELECT 1 FROM DUAL;'"] 
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  # Spring Boot application service
  books-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books-api
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521:XE
      - SPRING_DATASOURCE_USERNAME=Maya
      - SPRING_DATASOURCE_PASSWORD=Maya
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  oracle-data:
    driver: local