# Application configuration
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: books-authors-api
  
  # Database configuration
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

# OpenAPI Documentation configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.books.api.controller

# Swagger Information
swagger:
  title: Books and Authors API
  description: RESTful API for managing books and authors
  version: 1.0.0
  contact:
    name: API Support Team
    url: https://github.com/books-authors-api
    email: support@books-authors.com

# Security configuration
security:
  secret-key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}

# Rate Limiting configuration
rate-limiting:
  enabled: true
  # Default rate limit for all endpoints
  default:
    limit: 100
    refresh-period: 60
    time-unit: SECONDS
  # Specific endpoint rate limits
  endpoints:
    - pattern: /api/books
      limit: 50
      refresh-period: 60
      time-unit: SECONDS
    - pattern: /api/authors
      limit: 50
      refresh-period: 60
      time-unit: SECONDS
    - pattern: /api/authors/generate-token
      limit: 10
      refresh-period: 60
      time-unit: SECONDS
  # Strategy: IP_ADDRESS, USER, TOKEN
  strategy: IP_ADDRESS
  # Response headers
  response-headers: true

# CORS configuration
cors:
  enabled: true
  allowed-origins:
    - http://localhost:3000
    - https://books-authors-app.com
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
  allowed-headers:
    - Authorization
    - Content-Type
    - Accept
  exposed-headers:
    - X-RateLimit-Limit
    - X-RateLimit-Remaining
    - X-RateLimit-Reset
  allow-credentials: true
  max-age: 3600

# Logging configuration
logging:
  level:
    root: INFO
    com.books: DEBUG
    org.springframework.jdbc.core: DEBUG